# Stage 0: Build stage
FROM node:18.18-alpine as build-stage

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Copy file package.json và package-lock.json vào container
COPY package.json package-lock.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn vào container
COPY . .

# Build ứng dụng Vite
RUN npm run build

# Dùng Nginx để phục vụ ứng dụng Vite
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
# Copy file build từ bước trước vào thư mục của Nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY --from=build-stage /app/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Khởi động Nginx
CMD ["nginx", "-g", "daemon off;"]

# Build Docker image
# docker build -t my-vite-app .

# Chạy container
# docker run -d -p 3000:80 --name vite-container my-vite-app
